//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterRoutineManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Routines = new HashSet<Routine>();
            this.StudentCourseEnrollments = new HashSet<StudentCourseEnrollment>();
            this.TeacherAppointments = new HashSet<TeacherAppointment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Term { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> ModifedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Routine> Routines { get; set; }
        public virtual ICollection<StudentCourseEnrollment> StudentCourseEnrollments { get; set; }
        public virtual ICollection<TeacherAppointment> TeacherAppointments { get; set; }
    }
}
