//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterRoutineManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Routines = new HashSet<Routine>();
        }
    
        public int Id { get; set; }
        public string No { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Routine> Routines { get; set; }
    }
}
