//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterRoutineManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SemesterRoutineMSDBEntities : DbContext
    {
        public SemesterRoutineMSDBEntities()
            : base("name=SemesterRoutineMSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<StudentCourseEnrollment> StudentCourseEnrollments { get; set; }
        public DbSet<TeacherAppointment> TeacherAppointments { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<Routine> Routines { get; set; }
        public DbSet<TimeSpan> TimeSpans { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<WeekDay> WeekDays { get; set; }
        public DbSet<Session> Sessions { get; set; }
    }
}
