//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterRoutineManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.StudentCourseEnrollments = new HashSet<StudentCourseEnrollment>();
            this.TeacherAppointments = new HashSet<TeacherAppointment>();
            this.Routines = new HashSet<Routine>();
            this.Courses = new HashSet<Course>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public bool Status { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        public virtual ICollection<StudentCourseEnrollment> StudentCourseEnrollments { get; set; }
        public virtual ICollection<TeacherAppointment> TeacherAppointments { get; set; }
        public virtual ICollection<Routine> Routines { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}
